apiVersion: v1
kind: ConfigMap
metadata:
  name: markhor-config
  namespace: markhor
data:
  config.yaml: |
    logging:
      level: info

    tls:
      enabled: true
      certPath: /etc/markhor/tls/tls.crt
      keyPath: /etc/markhor/tls/tls.key
