apiVersion: apps/v1
kind: Deployment
metadata:
  name: markhor
  namespace: markhor
  labels:
    app.kubernetes.io/name: markhor
    app.kubernetes.io/instance: markhor-default
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: markhor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: markhor
  template:
    metadata:
      labels:
        app: markhor
    spec:
      serviceAccountName: markhor-service-account
      containers:
        - name: markhor
          image: ghcr.io/markhork8s/markhor:1.0.0
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /age-secrets/age_keys.txt
          ports:
            - name: health
              containerPort: 8000
            - name: validationhook
              containerPort: 443
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
              scheme: HTTPS
              httpHeaders:
                - name: Host
                  value: markhor.markhor.svc
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
              scheme: HTTPS
              httpHeaders:
                - name: Host
                  value: markhor.markhor.svc
            initialDelaySeconds: 2
          volumeMounts:
            - name: markhor-config
              mountPath: /etc/markhor
              readOnly: true
            - name: markhor-age
              mountPath: /age-secrets
              readOnly: true
            - name: markhor-tls
              mountPath: /etc/markhor/tls
              readOnly: true
      volumes:
        - name: markhor-config
          configMap:
            name: markhor-config
        - name: markhor-age
          secret:
            secretName: markhor-age-secret
        - name: markhor-tls
          secret:
            secretName: markhor-tls-secret
