apiVersion: v1
kind: Secret
metadata:
  name: markhor-age-secret
  namespace: markhor
  labels:
    app.kubernetes.io/name: markhor
    app.kubernetes.io/instance: markhor-default
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: markhor
stringData:
  age_keys.txt: "AGE-SECRET-KEY-1LYQ3PW...."
