apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: markhor
  name: markhor-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch", "delete"]
- apiGroups: ["markhor.example.com"]
  resources: ["markhorsecrets"]
  verbs: ["list", "watch"]
