apiVersion: v1
kind: ServiceAccount
metadata:
  name: markhor-service-account
  namespace: markhor
  labels:
    app.kubernetes.io/name: markhor
    app.kubernetes.io/instance: markhor-default
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: markhor
