apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: markhor-validation-webhook-config
webhooks:
  - name: validate.markhork8s.github.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    rules:
      - apiGroups:
          - markhork8s.github.io
        apiVersions:
          - v1
        resources:
          - markhorsecrets
        operations:
          - CREATE
          - UPDATE
        scope: Namespaced
    clientConfig:
      service:
        name: markhor
        namespace: markhor
        path: /validate
      # kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}'
      caBundle: "_CA_BUNDLE_HERE_"
