apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: markhorsecrets.markhork8s.github.io
spec:
  group: markhork8s.github.io
  names:
    kind: MarkhorSecret
    plural: markhorsecrets
    singular: markhorsecret
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - apiVersion
            - kind
            - sops
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            type:
              type: string
            immutable:
              type: boolean
            data:
              type: object
              additionalProperties:
                type: string
            stringData:
              type: object
              additionalProperties:
                type: string
            sops:
              type: object
              required:
                - mac
                - lastmodified
                - version
              properties:
                kms:
                  type: array
                  items:
                    type: object
                    properties:
                      arn:
                        type: string
                      created_at:
                        type: string
                      enc:
                        type: string
                      aws_profile:
                        type: string
                      role:
                        type: string
                    additionalProperties:
                      type: string
                gcp_kms:
                  type: array
                  items:
                    type: object
                azure_kv:
                  type: array
                  items:
                    type: object
                hc_vault:
                  type: array
                  items:
                    type: object
                age:
                  type: array
                  items:
                    type: object
                    properties:
                      recipient:
                        type: string
                      enc:
                        type: string
                lastmodified:
                  type: string
                mac:
                  type: string
                pgp:
                  type: array
                  items:
                    type: string
                encrypted_regex:
                  type: string
                version:
                  type: string
            markhorParams:
              type: object
              properties:
                hierarchySeparator:
                  type: string
                managedLabel:
                  type: string
                order:
                  type: array
                  items:
                    type: string
