apiVersion: markhor.example.com/v1
kind: MarkhorSecret
metadata:
    name: sample-secret
    namespace: default
markhorParams:
    hierarchySeparator: .
    managedAnnotation: custom_managed_by
    order:
        - apiVersion
        - kind
        - metadata.name
        - metadata.namespace
        - markhorParams.hierarchySeparator
        - markhorParams.managedAnnotation
        - markhorParams.order
        - type
        - data.session
        - stringData.another
type: Opaque
data:
    session: ENC[AES256_GCM,data:db20CmruczjrkeUm8HpZ4SJQiEsjcotkDTWAiCH82aN2KdgPicrxssY54bByURmPcs1fWw/PqJAhopweEP8OSyHNq0xtoE5bPxojLYgUACXeXsemZNzW1Q==,iv:xz3yccQDVnhxvhdC8G5toqSjsJUXEB2OrOMlVJUR6CA=,tag:orTwH1aGy1MRtGUzwD5B/Q==,type:str]
stringData:
    another: ENC[AES256_GCM,data:DFSmTEKy7JRF9SdQijDtMxZkExbgoQ==,iv:7zddvpH/F3T1oQcdE6E8N/0kBVEsSXzLWs4A3i86G28=,tag:3qc3VAXBZe03KPe61kpJdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apq7ck5adq6dkd0c242phl42fsurvpxvt9pwk0qg7ahdex7fqppqj8pe8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2S2lNV3lQRkI0bW01SFpV
            b1A5YnpCaTA0OTNleVhJNFR2V0xKOVBINzFvCjFHUzdlWlV6ejd4ZVNtTnJ3Zlhu
            WDlEOXh1bXJRL2ZmbHFXV0ZnMUdqU2MKLS0tIFRBWXRoM0pLaGFabU0wdUpaSE4y
            bDkwYVI5SlRFaWtiWjhsRTdaendVdDAK5iQe+tf5+AwBx65iTcyHLoPYWu0Z+P8t
            GYiO/CHYMPV/1NDZRB4bWBDdCZppR1kAq18g8sTGiILEotY9KVFJEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-09T20:37:07Z"
    mac: ENC[AES256_GCM,data:zfKLZKDQoo2lDDW1e4v79fLfwHlao+bViN+wZM9yYAcmScJ2y/lxzd7NlJ2mATeScWUur57aTaCBaslfYuCiSZkHJRPuSjmZLKrUBJSwHmoYIu7GgTQmgPl/T+7RzR3fDZXztTZw4tKusvmizs2KTMTSUbyQ9S8L36xHkKoKiaM=,iv:dnLLaKANUMJl07trmN5DBkyrpOMXUHOfVOIc0qhAVnY=,tag:jZi1a5qlD7fxUSyeIY5Peg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
