name: Check code quality

jobs:
  check_quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check formatting w/ gofmt
      run: |
        gofmt -l -s -w .
        git diff --exit-code

    - name: Run go vet
      run: |
        go vet ./...

    - name: Run staticcheck
      run: |
        staticcheck ./...

    - name: Run Gosec Security Scanner
      uses: securego/gosec@v2.18.2
      with:
        args: ./...

    - name: Run govulncheck
      run: |
        govulncheck ./...
