apiVersion: apps/v1
kind: Deployment
metadata:
  name: markhor
  namespace: markhor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: markhor
  template:
    metadata:
      labels:
        app: markhor
    spec:
      serviceAccountName: markhor-service-account
      containers:
      - name: markhor
        image: markhor/markhor:latest
        imagePullPolicy: Never
