apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: markhor
  name: markhor-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "create", "update", "delete"]
- apiGroups: ["markhor.example.com"]
  resources: ["markhorsecrets", "customorderings"]
  verbs: ["list", "watch"]
