apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: markhor-role-binding
  namespace: markhor
subjects:
- kind: ServiceAccount
  name: markhor-service-account
  namespace: markhor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: markhor-role
