apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sopssecrets.sops-k8s.example.com
spec:
  group: sops-k8s.example.com
  names:
    kind: SopsSecret
    plural: sopssecrets
    singular: sopssecret
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: 
            - apiVersion
            - kind
            - type
            - sops
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            type:
              type: string
            data:
              type: object
              additionalProperties:
                type: string
            stringData:
              type: object
              additionalProperties:
                type: string
            sops:
              type: object
              properties:
                kms:
                  type: array
                  items:
                    type: string
                gcp_kms:
                  type: array
                  items:
                    type: string
                azure_kv:
                  type: array
                  items:
                    type: string
                hc_vault:
                  type: array
                  items:
                    type: string
                age:
                  type: array
                  items:
                    type: object
                    properties:
                      recipient:
                        type: string
                      enc:
                        type: string
                lastmodified:
                  type: string
                mac:
                  type: string
                pgp:
                  type: array
                  items:
                    type: string
                encrypted_regex:
                  type: string
                version:
                  type: string
