name: Check code quality and tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check_quality:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: go1.22.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check formatting w/ gofmt
        run: |
          gofmt -l -s -w .
          git diff --exit-code

      - name: Run go generate
        run: |
          export PATH="$(go env GOPATH)/bin:$PATH"
          go get sigs.k8s.io/controller-tools
          go install sigs.k8s.io/controller-tools/cmd/controller-gen
          go generate ./...

      - name: Run go vet
        run: |
          go vet ./...

      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.20.0
        env:
          GOROOT: ""
        with:
          args: ./...

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"

      - name: Run govulncheck
        run: |
          # Install govulncheck
          go install golang.org/x/vuln/cmd/govulncheck@latest
          # Update path
          export PATH="$(go env GOPATH)/bin:$PATH"
          # Replace go version in go.mod otherwise govulncheck freaks out
          #sed -i 's/^go .*$/go 1.18.0/' go.mod
          govulncheck ./...

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run go generate
        run: |
          export PATH="$(go env GOPATH)/bin:$PATH"
          go install sigs.k8s.io/controller-tools/cmd/controller-gen
          go generate ./...

      - name: Test code
        run: go test ./...
